<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>2.0.2</Version>
    <Title>ArgentSea Microsoft Orleans persistence for SQL Server</Title>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	<Copyright>© John Hicks</Copyright>
    <Description>Extension to enable ArgentSea to serve as a data provider for Microsoft Orleans, using standard SQL Server tables and stored procedures.</Description>
	<PackageIcon>argentsea-logo.png</PackageIcon>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

	<PropertyGroup>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Orleans.Runtime" Version="9.2.1" />
		<PackageReference Include="Microsoft.Orleans.Reminders" Version="9.2.1" />
		<PackageReference Include="Microsoft.Orleans.Sdk" Version="9.2.1" />
		<None Include="argentsea-logo.png" Pack="true" PackagePath="\" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ArgentSea.Orleans\src\ArgentSea.Orleans.csproj" />
    <ProjectReference Include="..\ArgentSea.Shared\src\ArgentSea.csproj" />
    <ProjectReference Include="..\ArgentSea.Sql\src\ArgentSea.Sql.csproj" />
  </ItemGroup>

</Project>
