<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <FileVersion>2.0.0.0</FileVersion>
    <Description>This library depends on the core ArgentSea library and provides extensions to allow it to provide storage services to Microsoft Orleans..</Description>
	<Copyright>© John Hicks</Copyright>
	<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	<Version>2.0.2</Version>
    <Title>ArgentSea core library for Microsoft Orleans persistence</Title>
	<Description>Abstrations which enable ArgentSea to serve as a data provider for Microsoft Orleans.</Description>
	<PackageIcon>argentsea-logo.png</PackageIcon>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

	<PropertyGroup>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	</PropertyGroup>

	<ItemGroup>
    <PackageReference Include="Microsoft.Orleans.Reminders" Version="9.1.2" />
    <PackageReference Include="Microsoft.Orleans.Runtime" Version="9.1.2" />
    <PackageReference Include="Microsoft.Orleans.Sdk" Version="9.1.2" />
	<None Include="readme.md" Pack="true" PackagePath="\" />
	<None Include="argentsea-logo.png" Pack="true" PackagePath="\" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ArgentSea.Shared\src\ArgentSea.csproj" />
  </ItemGroup>
	<ItemGroup>
		<InternalsVisibleTo Include="$(MSBuildProjectName).Test" />
	</ItemGroup>

</Project>
